image: gradle:jdk17

stages:
  - build
  - test

build-job:
  stage: build
  only:
    - master
    - merge_requests
    - pushes
  script:
    - ./gradlew build

test-job:
  stage: test
  only:
    - master
    - merge_requests
    - pushes
  script:
    - ./gradlew test