create table region (
    id serial not null primary key,
    name varchar(100) not null
);

insert into region(name) values ('Республика Адыгея');
insert into region(name) values ('Республика Алтай');
insert into region(name) values ('Алтайский край');
insert into region(name) values ('Амурская область');
insert into region(name) values ('Архангельская область');
insert into region(name) values ('Астраханская область');
insert into region(name) values ('Республика Башкортостан');
insert into region(name) values ('Республика Бурятия');
insert into region(name) values ('Белгородская область');
insert into region(name) values ('Брянская область');
insert into region(name) values ('Владимирская область');
insert into region(name) values ('Волгоградская область');
insert into region(name) values ('Вологодская область');
insert into region(name) values ('Воронежская область');
insert into region(name) values ('Республика Дагестан');
insert into region(name) values ('Донецкая народная республика');
insert into region(name) values ('Еврейская автономная область');
insert into region(name) values ('Забайкальский край');
insert into region(name) values ('Запорожская область');
insert into region(name) values ('Республика Ингушетия');
insert into region(name) values ('Ивановская область');
insert into region(name) values ('Иркутская область');
insert into region(name) values ('Кабардино-Балкарская Республика');
insert into region(name) values ('Республика Калмыкия');
insert into region(name) values ('Карачаево-Черкесская Республика');
insert into region(name) values ('Республика Карелия');
insert into region(name) values ('Республика Коми');
insert into region(name) values ('Республика Крым');
insert into region(name) values ('Камчатский край');
insert into region(name) values ('Краснодарский край');
insert into region(name) values ('Красноярский край');
insert into region(name) values ('Калининградская область');
insert into region(name) values ('Калужская область');
insert into region(name) values ('Кемеровская область');
insert into region(name) values ('Кировская область');
insert into region(name) values ('Костромская область');
insert into region(name) values ('Курганская область');
insert into region(name) values ('Курская область');
insert into region(name) values ('Ленинградская область');
insert into region(name) values ('Липецкая область');
insert into region(name) values ('Луганская народная республика');
insert into region(name) values ('Республика Марий Эл');
insert into region(name) values ('Республика Мордовия');
insert into region(name) values ('Магаданская область');
insert into region(name) values ('Московская область');
insert into region(name) values ('Мурманская область');
insert into region(name) values ('Москва');
insert into region(name) values ('Нижегородская область');
insert into region(name) values ('Новгородская область');
insert into region(name) values ('Новосибирская область');
insert into region(name) values ('Ненецкий автономный округ');
insert into region(name) values ('Омская область');
insert into region(name) values ('Оренбургская область');
insert into region(name) values ('Орловская область');
insert into region(name) values ('Пермский край');
insert into region(name) values ('Приморский край');
insert into region(name) values ('Пензенская область');
insert into region(name) values ('Псковская область');
insert into region(name) values ('Ростовская область');
insert into region(name) values ('Рязанская область');
insert into region(name) values ('Республика Саха (Якутия)');
insert into region(name) values ('Республика Северная Осетия — Алания');
insert into region(name) values ('Ставропольский край');
insert into region(name) values ('Самарская область');
insert into region(name) values ('Саратовская область');
insert into region(name) values ('Сахалинская область');
insert into region(name) values ('Свердловская область');
insert into region(name) values ('Смоленская область');
insert into region(name) values ('Санкт-Петербург');
insert into region(name) values ('Севастополь');
insert into region(name) values ('Республика Татарстан');
insert into region(name) values ('Республика Тыва');
insert into region(name) values ('Тамбовская область');
insert into region(name) values ('Тверская область');
insert into region(name) values ('Томская область');
insert into region(name) values ('Тульская область');
insert into region(name) values ('Тюменская область');
insert into region(name) values ('Удмуртская Республика');
insert into region(name) values ('Ульяновская область');
insert into region(name) values ('Республика Хакасия');
insert into region(name) values ('Хабаровский край');
insert into region(name) values ('Херсонская область');
insert into region(name) values ('Ханты-Мансийский автономный округ — Югра');
insert into region(name) values ('Чеченская Республика');
insert into region(name) values ('Чувашская Республика');
insert into region(name) values ('Челябинская область');
insert into region(name) values ('Чукотский автономный округ');
insert into region(name) values ('Ярославская область');
insert into region(name) values ('Ямало-Ненецкий автономный округ');